### ISSUE TITLE
Need to increase array for number of structures in StateCU

### ISSUE THREAD

**Issue by ErinMWilson** [OpenCDSS/cdss-app-statecu-fortran#36]
----------------  -----------------  ----------------  ---------------- 
When submitting a feature or enhancement request:

1. Explain briefly what the enhancement is and why you think it would be useful.
2. Provide any other necessary or useful information regarding your issue, such as (code) examples or related links.

---

When submitting a bug report, please follow the following template:
----------------  -----------------  ----------------  ---------------- 

### Summary

...

### Expected behavior

...

### Actual behavior

...

### Steps to reproduce

1. First step
2. Second step
3. Third step

### Environment

* Operating system and version:
* [ ] Windows ...
* [ ] Mac OS ...
* [ ] Linux ...

If working in the developer environment:
* Compiler version
* Other tool version

**Comment by kelleythompson** [comment]
WWG submitted by Brenna increased structure array in gcommon.inc from 1200 to 1300 for use in ArkDSS.
