### ISSUE TITLE
Need to be able to run StateCU without Climate Files when using an RCR

### ISSUE THREAD

**Issue by bmefford45** [OpenCDSS/cdss-app-statecu-fortran#37]
----------------  -----------------  ----------------  ---------------- 
When submitting a feature or enhancement request:

1. This enhancement would allow users to not have to create fake climate files or select a crop consumptive use method when using an RCR file. 
2. Due to StateCUASCEpt using an RCR will be come more common with StateCU, it's important to be able to run the program without having to create many files you do not need.

**Comment by smalers** [comment]
StateMod has something similar and if I remember right the term 'dummy file' is used.  Perhaps just use a filename "na" or similar in the response file?  Being explicit will ensure that input checks know that the file is meant to be missing.

Or, add another command line parameter to indicate that the files are not used.  Command line parameters generally override other input.

**Comment by bmefford45** [comment]
Thanks Steve. Right now StateCU also goes through all the crop consumptive use calculations, so we want to update it so it skips those when an RCR is present.

**Comment by macphersonbr** [comment]
@bmefford45 - does Erin still have plans to work on StateCU code as part of ArkDSS? Could she address this issue there? Or should I plan for another way to get this work done?

**Comment by bmefford45** [comment]
Version 14.3.0 Solves this issue. Closing Issue.

**Comment by kelleythompson** [comment]
Attached commit to issue
